#!/bin/sh
file_init() {
	if [ -n "$XDG_DATA_HOME" ]
	then
		DIR="$XDG_DATA_HOME/xlabel"
	else
		DIR="$HOME/.local/share/xlabel"
	fi

	if [ ! -e "$DIR" ]
	then
		mkdir "$DIR"
	fi
	
	FILE="$DIR/xlabel.txt"
	touch "$FILE"
}

add_label() {
	if [ -z "$WINDOW" ]
	then
		WINDOW=$(xdotool getactivewindow)
	fi

	if grep "$WINDOW" "$FILE" &> /dev/null
	then
		echo "That window already has a label." 1>&2
	else
		echo "$WINDOW	$LABEL" >> "$FILE"
	fi
}

raise_window() {
	# All the windows with the given label
	WINDOWS=$(grep "$LABEL" "$FILE" | cut -f 1)
	# A window with the given label
	WINDOW=$(echo "$WINDOWS" | head -1)

	# The active window
	ACTIVE=$(xdotool getactivewindow)

	if [ "$ACTIVE" = "$WINDOW" ]
	then
		WINDOW=$(echo "$WINDOWS" | head -2 | tail -1)
	fi

	# Try to raise WINDOW
	xdotool windowraise "$WINDOW" 

	# If you didn't manage to raise it, that means WINDOW doesn't exist -it has been closed-.
	# 	Update FILE.	
	while [ $? -ne 0 ] && grep  "$LABEL" "$FILE"
	do
		grep -v "$WINDOW" "$FILE" > "$DIR/xlabel.txt.tmp"
		mv "$DIR/xlabel.txt.tmp" "$FILE"
		WINDOWS=$(grep "$LABEL" "$FILE" | cut -f 1)
		WINDOW=$(echo "$WINDOWS" | head -1)
		if [ "$ACTIVE" = "$WINDOW" ]
		then
			WINDOW=$(echo "$WINDOWS" | head -2 | tail -1)
		fi
		xdotool windowraise "$WINDOW"
	done

}

print_help() {
	echo "

              _/            _/                  _/   
   _/    _/  _/    _/_/_/  _/_/_/      _/_/    _/    
    _/_/    _/  _/    _/  _/    _/  _/_/_/_/  _/     
 _/    _/  _/  _/    _/  _/    _/  _/        _/      
_/    _/  _/    _/_/_/  _/_/_/      _/_/_/  _/       
                                                     
"
	echo 'Usage: xlabel option 	

	-a <label> [window]
		Add label to window.
		If no window is passed, the active window is used.
	
	-d [window]
		Delete label from window.
		If no window is passed, the active window is used.

	-p
		Print the windows that have labels.
	
	-f <label>
		Find all windows with <label>.
	
	-r <label>
		Raise the window with <label>.
		If many windows with <label> exist, cycle through them.
	
	-c <label>
		Close all windows with <label>.
	
	-m <label>
		Minimize all windows with <label>.

	-s <label>
		Select a window by clicking on it and add label to that window.	
	
	-h 
		Print this menu.
			
	* Every window can have only one label.
	* [TODO] what is the WINDOW argument
	* The file where the information is stored, is located at 
			$XDG_DATA_HOME/xlabel/xlabel.txt 
				or
			$HOME/.local/share/xlabel/xlabel.txt 
				if $XDG_DATA_HOME is not defined.'
	}

while getopts "a:dpf:r:c:m:s:h" option
do

	case "$option"
		in 
			[afrcms])	LABEL="$OPTARG"
	esac

	case "$option"
		in
			a)	function=ADD;;
			d)  function=DELETE;;
			p) 	function=PRINT;;
			f)	function=FIND;;
			r)	function=RAISE;;
			c)	function=CLOSE;;
			m)	function=MINIMIZE;;
			s)	function=SELECT;;
			h) 	print_help;;
			\?)	print_help;;

		esac
done

shift $((OPTIND-1))

WINDOW=$1  							# WINDOW might be empty

file_init

case "$function" 
	in
		ADD) add_label;;
		REMOVE):;;
		SEARCH):;;
		RAISE)raise_window;;
		CLOSE):;;
		MINIMIZE):;;
esac	
